In [9]:
pip install pandas openpyxl

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [2]:
import numpy as np
import pandas as pd
import os

# Define the path to the Excel file
input_file_path = r'D:\Reach Validation\correction.xlsx'

# Check if the file exists at the specified path
if not os.path.exists(input_file_path):
    raise FileNotFoundError(f"The file at {input_file_path} does not exist. Please check the file path and try again.")

# Load the data from the Excel file
data_df = pd.read_excel(input_file_path, sheet_name='data')
target_df = pd.read_excel(input_file_path, sheet_name='target')

# Convert the data from the 'data' sheet to a NumPy array
data = data_df.values

# Extract headers from the 'data' sheet
headers = data_df.columns.tolist()

# Convert the target sums from the 'target' sheet to a NumPy array
target_sums = target_df.values.flatten()

# Calculate the current sum of each column
current_sums = np.sum(data, axis=0)

# Calculate the ratio for each column
ratios = target_sums / current_sums

# Adjust the values in the original table
adjusted_data = data * ratios

# Round the values to the nearest integer
adjusted_data = np.round(adjusted_data).astype(int)

# Create a DataFrame to save to Excel with the same headers as the input
adjusted_df = pd.DataFrame(adjusted_data, columns=headers)

# Define the output Excel file path
# Extract the folder path from the input file path
folder_path = os.path.dirname(input_file_path)
# Define the name of the output file
output_file_name = 'adjusted_data.xlsx'
# Combine folder path and file name to get the full path
output_file_path = os.path.join(folder_path, output_file_name)

# Save the DataFrame to an Excel file
adjusted_df.to_excel(output_file_path, index=False)

# Open the Excel file
os.startfile(output_file_path)

# Output the adjusted data to the console
print("Adjusted Data:")
print(adjusted_data)

Adjusted Data:
[[ 235  237  649  648  854  853]
 [ 501  546 1384 1493 1822 1965]
 [ 122  143  336  390  443  513]
 [ 529  564 1464 1543 1927 2031]
 [ 421  466 1163 1275 1532 1678]
 [ 640  710 1769 1942 2328 2556]
 [ 799  836 2208 2286 2907 3010]
 [ 575  621 1591 1698 2094 2235]
 [ 414  455 1145 1245 1507 1639]
 [ 854  871 2360 2383 3107 3137]
 [ 396  405 1094 1107 1441 1457]
 [ 826  974 2285 2663 3008 3506]]
